### ISSUE TITLE
Error since update to 0.0.1

### ISSUE THREAD

**Issue by dennisschumann** [fsaris/home-assistant-awox#14]
Since the latest update to 0.0.1 I get this error and lights are not available in HA:

``
Source: custom_components/awox/light.py:124
First occurred: 18:46:07 (1 occurrences)
Last logged: 18:46:07

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/awox/light.py", line 124, in device_info
    "model": self._model.replace('_', ' '),
AttributeError: 'bool' object has no attribute 'replace'``

**Comment by dennisschumann** [comment]
I have removed and reinstalled the Integration. The devices are discovered properly but now both are not available anymore and I get this log message:

`Logger: custom_components.awox.awox_mesh
Source: custom_components/awox/awox_mesh.py:83
Integration: AwoX MESH control (documentation, issues)
First occurred: 20:15:41 (2 occurrences)
Last logged: 20:15:44

[a4:c1:38:9b:21:97][Esstisch] Failed to connect, trying next device [Device disconnected]
[a4:c1:38:92:99:21][Küche] Failed to connect, trying next device [Failed to connect to peripheral a4:c1:38:92:99:21, addr type: public]`

**Comment by fsaris** [comment]
> `File "/config/custom_components/awox/light.py", line 124, in device_info
"model": self.model.replace('', ' '),
AttributeError: 'bool' object has no attribute 'replace'`


This is/was due to a bug in a previous version where the device info was not saved correctly.

Reinstall was indeed the proper fix.

Could you try to restart the integration (or HA).

Probably it will be able to connect then. Somehow the bluetooth device doesn't always want to reconnect properly after a not proper disconnect (looks like a issue in bluepy package)

**Comment by dennisschumann** [comment]
Thank you for the response.  I've completely un- and reinstalled the integration including a complete reboot.

Now, I only get this in the log - the discovered devices are still unavailable:

Logger: custom_components.awox.awox_mesh
Source: helpers/update_coordinator.py:166
Integration: AwoX MESH control (documentation, issues)
First occurred: 22:08:12 (1 occurrences)
Last logged: 22:08:12

Error fetching awox data: Command tread died!

**Comment by dennisschumann** [comment]
Works fine after reinstalling the integration and after a reboot. Thank you!
